import type {Metadata} from "next";
import "@/app/globals.css"
import {ThemeProvider} from "@/components/ui/theme-provider";
import React from "react";
import { Viewport } from "next";

export const metadata: Metadata = {
    title: "Omega | Sistema Cálculo Móveis MVA",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    themeColor: "#000000",
    width: "device-width",
    initialScale: 1,
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" suppressHydrationWarning>
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
