import type {Metadata} from "next";
import ClientHome from "@/components/home/client-home";

export const metadata: Metadata = {
    title: "Boreal | Móveis em Vidro e Alumínio",
    description: "Generated by create next app",
};

export default function Home() {

    return <ClientHome />;
}