import type {Metadata} from "next";
import "@/app/globals.css";
import {
    SidebarInset,
    SidebarProvider,
    SidebarTrigger,
} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/layout/app-sidebar";
import {Separator} from "@/components/ui/separator";
import {ThemeToggle} from "@/components/ui/theme-toggle";
import {DynamicBreadcrumb} from "@/components/layout/dynamic-breadcrump";
import React from "react";
import {auth} from "@/lib/auth";
import {redirect} from "next/navigation";
import {ThemeProvider} from "@/components/ui/theme-provider";
import {headers} from "next/headers";

export const metadata: Metadata = {
    title: "Omega | Sistema Cálculo Móveis MVA",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const data = await auth.api.getSession({
        headers:await headers()
    });

    if (!data?.session) {
        console.log("minha sessão" + data?.session);
        redirect("/login")
    }
    return (
  <>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
            <SidebarProvider>
                <AppSidebar user={data.user}/>
                <SidebarInset>
                    <header
                        className="flex h-16 shrink-0 items-center justify-between gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 px-4">
                        <div className="flex items-center gap-2">
                            <SidebarTrigger className="-ml-1"/>
                            <Separator
                                orientation="vertical"
                                className="mr-2 data-[orientation=vertical]:h-4"
                            />
                            <DynamicBreadcrumb/>
                        </div>
                        <ThemeToggle/>
                    </header>
                    {children}
                </SidebarInset>
            </SidebarProvider>
         </ThemeProvider>
     </>
);
}
